In [9]:
import numpy as np 

a1 = np.array([1,2,3,4,5])
print(a1)
print(np.shape(a1))
a1[3]=77
print(a1)

[1 2 3 4 5]
(5,)
[ 1  2  3 77  5]


In [10]:
index = np.array([1,3])
a1[index] = 0 
print(a1)

[1 0 3 0 5]


In [11]:
a1[index] += 5
print(a1)

[1 5 3 5 5]


In [13]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2[1,2]=10
print(a2)

[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


In [14]:
a2[2] = 0 
print(a2)

[[ 1  2  3]
 [ 4  5 10]
 [ 0  0  0]]


In [15]:
a2[:,1]=7 #슬라이스는 원본의 배열을 바꿈 
print(a2)

[[ 1  7  3]
 [ 4  7 10]
 [ 0  7  0]]


In [16]:
a2[1:,1]=3
print(a2)

[[ 1  7  3]
 [ 4  3 10]
 [ 0  3  0]]


In [17]:
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0 
print(a2)

[[1 0 3]
 [4 3 0]
 [0 3 0]]


In [18]:
print(a2)
b = np.delete(a2,2,axis=0) #axis가 0이면 row, 1이면 col 
print(a2) #원본배열 유지됨
print(b)

[[1 0 3]
 [4 3 0]
 [0 3 0]]
[[1 0 3]
 [4 3 0]
 [0 3 0]]
[[1 0 3]
 [4 3 0]]


In [20]:
b2 = a2[:2,:2].copy()
print(a2)
print(b2)
b2[:,1] =2
print(b2)

[[1 0 3]
 [4 3 0]
 [0 3 0]]
[[1 0]
 [4 3]]
[[1 2]
 [4 2]]


In [21]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])

a3[:,:,0]=0
print(a3)

[[[0 2 3]
  [0 5 6]
  [0 8 9]]

 [[0 2 3]
  [0 5 6]
  [0 8 9]]

 [[0 2 3]
  [0 5 6]
  [0 8 9]]]
