In [7]:
import numpy as np 

a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8],[9,10],[11,12]])

#행렬의 곱은 순서에 따른 다른 결과값
print(a.dot(b))
print(b.dot(a))

[[ 58  64]
 [139 154]]
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [8]:
a= np.array([[1,2],[4,5]])
b= np.array([[1,2],[1,5]])

print(a.dot(b))
print(b.dot(a))

[[ 3 12]
 [ 9 33]]
[[ 9 12]
 [21 27]]


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [10]:
a= np.array([[1,2],[4,5]])
b= np.array(np.identity(2))
print(a.dot(b))

a= np.array([[1,2],[4,5],[6,7]])
b= np.array(np.identity(2))
print(a.dot(b))

[[1. 2.]
 [4. 5.]]
[[1. 2.]
 [4. 5.]
 [6. 7.]]


In [11]:
#역행렬을 구하기 
a= np.array([[1,2],[4,5]])
print(a)
b = np.linalg.inv(a)
print(b)
print(a.dot(b))

[[1 2]
 [4 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [17]:
#역행렬을 구하기 
A = np.array([[1, 2, 1], [1, 2, 3], [2, 3, -1]])
A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.dot(A))

[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [-0.5  0.5 -0. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#역행렬을 가지지 않는 함수 
m = np.array([[2,6],[1,3]])
n = np.linalg.inv(m)
print(n)
print(m.dot(n))

LinAlgError: Singular matrix

In [19]:
A = np.array([[4, 5, 1], [3, 2, 1], [1, 4, -1]])

A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.dot(A))

[[-1.          1.5         0.5       ]
 [ 0.66666667 -0.83333333 -0.16666667]
 [ 1.66666667 -1.83333333 -1.16666667]]
[[ 1.00000000e+00  4.44089210e-16  1.11022302e-16]
 [-1.94289029e-16  1.00000000e+00 -2.77555756e-17]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00]]


In [12]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

#행렬의 스칼라곱 (스칼라곱은 실수 * 행렬 )
print(-1*a)
print(7.81*a)
print(0*a)
print((1/2)*a)
print(np.pi*a)
print(np.e*a)
print(np.sqrt(2)*a)
print(np.sqrt(a))


[[1 2 3]
 [4 5 6]]
[[-1 -2 -3]
 [-4 -5 -6]]
[[ 7.81 15.62 23.43]
 [31.24 39.05 46.86]]
[[0 0 0]
 [0 0 0]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 3.14159265  6.28318531  9.42477796]
 [12.56637061 15.70796327 18.84955592]]
[[ 2.71828183  5.43656366  8.15484549]
 [10.87312731 13.59140914 16.30969097]]
[[1.41421356 2.82842712 4.24264069]
 [5.65685425 7.07106781 8.48528137]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
import numpy as np
aArr = np.array([[1,2,3],[3,2,1]])
print(aArr)
print(aArr.T)

[[1 2 3]
 [3 2 1]]
[[1 3]
 [2 2]
 [3 1]]


In [8]:
aArr = np.array([[1,2,3],[3,2,1]])
bArr =  np.array([[1,2],[3,4],[5,6]])
rArr = aArr.dot(bArr)
print(rArr.T)

[[22 14]
 [28 20]]


In [9]:
print((bArr.T).dot(aArr.T))

[[22 14]
 [28 20]]


In [12]:
aMat = np.array([[2,-1],[1,1]])

#bMat = np.array([x,y])

NameError: name 'x' is not defined